global:
  resolve_timeout: 1m
  smtp_smarthost: 'int.postfix.smedia.fra-1.smhss.de:25'
  smtp_from: 'alertmanager@seibert-media.net'
  smtp_require_tls: false

# The directory from which notification templates are read.
templates:
- '/etc/alertmanager/template/*.tmpl'

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  group_by: ['alertname', 'cluster', 'service']
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  - receiver: 'team-inf'
    group_by: ['alertname', 'cluster', 'service']
    match_re:
      severity: warning|critical

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname', 'cluster', 'service']


receivers:
- name: 'team-inf'
  email_configs:
  - to: 'infinity@seibert-media.net'
- name: 'default'